[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["mkdir -p media/images media/audio media/videos media/documents logs"]

[start]
cmd = "python web/run_admin.py"
